### ISSUE TITLE
Converted file contains non existing date 31.09.

### ISSUE THREAD

**Issue by cadamini** [tobilen/csv-tz-converter#2]
We get an entire day with date 31.09. when using your UTC converter with a file which contains the date 1.10.2019 - any idea why?

Attached files for testing:

[Motibot CSV Import_UTC.csv.txt](https://github.com/tobilen/csv-tz-converter/files/3579618/Motibot.CSV.Import_UTC.csv.txt)
[Motibot CSV Import.csv_convertable.csv.txt](https://github.com/tobilen/csv-tz-converter/files/3579619/Motibot.CSV.Import.csv_convertable.csv.txt)

**Comment by tobilen** [comment]
fixed with https://github.com/tobilen/csv-tz-converter/releases/tag/1.1.0
